CREATE TABLE persons (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  label TEXT NOT NULL UNIQUE,
  active BOOLEAN DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recognition_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  person_label TEXT,
  confidence REAL NOT NULL,
  recognized_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
